/**
 * lib/skills.mjs — load bundled skill definitions from the build-time
 * manifest and register them into the skill registry.
 *
 * The manifest is generated by build.mjs (see skills/manifest.json): every
 * SKILL.md's metadata is parsed at BUILD time and the body's byte offset is
 * recorded, so this module needs NO YAML parser at runtime. Registration uses
 * the registry's public runtime-skill channel (ctx.skills.register), which the
 * registry validates on load (content and source are required fields).
 */
import { existsSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

/**
 * Read the manifest and build the runtime-skill definitions.
 * @param {string} skillsRoot - the bundled skills directory.
 * @param {string} [manifestFile] - manifest path; defaults to skillsRoot/manifest.json.
 * @returns {Array<object>} definitions shaped for ctx.skills.register().
 */
export function loadSkillDefinitions(skillsRoot, manifestFile = join(skillsRoot, 'manifest.json')) {
  if (!existsSync(manifestFile)) throw new Error(`skill manifest not found: ${manifestFile}`)
  const entries = JSON.parse(readFileSync(manifestFile, 'utf8'))
  if (!Array.isArray(entries)) throw new Error(`skill manifest must be an array: ${manifestFile}`)
  return entries.map((entry) => {
    if (typeof entry?.name !== 'string' || entry.name.length === 0) throw new Error('skill entry missing name')
    if (typeof entry?.description !== 'string' || entry.description.length === 0) {
      throw new Error(`skill "${entry.name}" missing description`)
    }
    if (typeof entry?.file !== 'string') throw new Error(`skill "${entry.name}" missing file`)
    const file = join(skillsRoot, entry.file)
    const buffer = readFileSync(file)
    if (!Number.isInteger(entry.contentOffset) || entry.contentOffset < 0 || entry.contentOffset > buffer.length) {
      throw new Error(`skill "${entry.name}" has invalid contentOffset`)
    }
    return {
      name: entry.name,
      description: entry.description,
      ...(entry.whenToUse !== undefined ? { whenToUse: entry.whenToUse } : {}),
      ...(entry.invocation !== undefined ? { invocation: entry.invocation } : {}),
      content: buffer.subarray(entry.contentOffset).toString('utf8'),
      source: 'superpowers',
      resourceBase: { kind: 'directory', path: join(skillsRoot, dirname(entry.file)) },
      path: file,
    }
  })
}

/**
 * Register definitions into the skill registry (global layer when called from
 * a host-composition plugin).
 * @param {{ skills: { register: (definition: object) => unknown } }} ctx
 * @param {Array<object>} definitions - from loadSkillDefinitions().
 * @returns {number} the number of definitions registered.
 */
export function registerSkills(ctx, definitions) {
  for (const definition of definitions) ctx.skills.register(definition)
  return definitions.length
}
